# Configure Using Gemfile
# gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_app_development

test:
  <<: *default
  database: portfolio_app_test

production:
  <<: *default
  database: i_know_that_production
  username: i_know_that
  password: <%= ENV['PORTFOLIO_APP_DATABASE_PASSWORD'] %>
